version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/home/app
    working_dir: /home/app
    tty: true
    ports:
      - 4200:4200
    dns:
      - 8.8.8.8

  nginx:
    image: nginx:1.22-alpine
    volumes:
      - ./.docker/proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/home/public
    ports:
      - "80:80"
    depends_on:
      - app


